config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:index]

  root 'users#index'
  resources :users do 
    resources :posts 
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord    
    attr_accessor :remember_token

    before_save { self.email = email.downcase }

    validates :username, presence: true, length: { maximum: 50 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, 
              format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    
    validates :password, presence: true, length: { minimum: 6 }

    has_secure_password

    has_many :posts

    # Hashes any string
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)

    end

    # Returns a random token
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # Update the remember_digest column with our generated remember_token
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if remember_token matches the digest
    def authenticated?(remember_token)
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    include UsersHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    before_action :find_post, except: [:index, :new, :create]
    before_action :find_user, except: [:index]

    def index 
        @post = Post.all
        @post.each do |post|
            @author = User.where(id: post.user_id).first
        end
    end

    def new 
        @post = Post.new
    end

    def create
        @post = @user.posts.create(post_params)
        if @post.save
            redirect_to user_post_path(@user, @post.id)
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def update
        @post.update(post_params)
        redirect_to user_post_path(@user, @post.id)
    end

    def destroy
        @post.destroy
        redirect_to user_path(@user)
    end

    private

    def find_user
        @user = User.find(params[:user_id])
    end

    def find_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            log_in user
            # remember user
            redirect_to user
        else 
            render 'new'
        end
    end

    def destroy
        log_out
        redirect_to root_url
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :logged_in_user, only: [:show]

    def index
    end

    def new
        @user = User.new 
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in @user
            redirect_to @user
        else
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_digest)
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
              log_in user
              @current_user = user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper

    def logged_in_user
        unless logged_in? 
            flash[:danger] = "Please log in"
            redirect_to login_url
        end
    end
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for([@user, @user.posts.build]) do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>

    <%= f.label :content %><br>
    <%= f.text_field :content %><br><br>

    <%= f.submit :Submit %>
<% end %>

app/views/posts/edit.html.erb
<h1> Edit your post </h1>

<%= form_for ([@user, @post]) do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br><br>

    <%= f.label :content %><br>
    <%= f.text_field :content %><br><br>

    <%= f.submit :Submit %>
<% end %>

app/views/posts/index.html.erb
<% if !@post.empty? %>
    <% @post.each do |post| %>
        <h1> <%= post.title %><br> </h1>
        <p> <%= post.content %><br> </p>
        <%= post.created_at.strftime("%B %d %Y, %l:%M%P") %>
        <% if logged_in? %>
            <p> - <%= @author.username %> </p>
        <% end %>
        <hr>
    <% end %>
<% else %>
    <h1> There are no posts here... </h1>
<% end %>

<%= link_to "<<Back", root_path %>

app/views/posts/new.html.erb
<h1> Create a New Post </h1>
<%= render 'form' %><br>
<%= link_to "<< Back", user_path(@user) %>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<p> <%= @post.content %> <p>
<%= link_to "Edit", edit_user_post_path(@user, @post) %>
<%= link_to "Delete", user_post_path(@user, @post), method: :delete, data: {confirm: "Are you sure?"} %><br>
<%= link_to "<< Back", user_path(@user) %>

app/views/users/index.html.erb
<h1> Welcome to Members Only! </h1>
<%= link_to "See all Posts", posts_path %> <br>
<% if logged_in? %>
    <%= link_to "Go to dashboard", user_path(session[:user_id]) %>
    <%= link_to "Logout", '/logout', method: :delete, data: {confirm: "Are you sure you want to log out?"}%>
<% else %>
    <%= link_to "Sign Up", new_user_path %>
    <%= link_to "Login",  '/login' %>
<% end %>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= form_for @user do |f| %>
    <%= f.label :username %><br>
    <%= f.text_field :username %><br><br>

    <%= f.label :email %><br>
    <%= f.email_field :email %><br><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br><br>
    <%= f.submit :Submit %>
<% end %>

app/views/users/show.html.erb
<h1> Hello <%= @user.username %> </h1>
<% if @user.posts %>
    <% @user.posts.each do |post| %>
        <%= link_to post.title, user_post_path(@user, post) %><br>
    <% end %>
<% end %>
<br>
<%= link_to "See all Posts", posts_path %> <br>
<%= link_to "Create a Post", new_user_post_path(@user) %><br>